global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'json-lite-monitor'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OP2 Lite FastAPI metrics
  - job_name: 'op2-lite'
    static_configs:
      - targets: ['op2-lite:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Docker daemon metrics (optional)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml'