name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push OP1 Large
        uses: docker/build-push-action@v5
        with:
          context: op1_large
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:op1-large-${{ github.ref_name }}

      - name: Build and push OP2 Lite
        uses: docker/build-push-action@v5
        with:
          context: op2_lite
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:op2-lite-${{ github.ref_name }}
